name: 'haibun web accessibility test'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  e2e_test_and_publish:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.44.0
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test
